import type { Metadata } from "next";
import "./globals.css";
import PageAnimatePresence from '../components/PageAnimatePresence'
import Header from "@/components/Header";
import MainMenu from "@/components/MainMenu";

 
export const metadata: Metadata = {
  title: "LifeClicks",
  description: "Generated by very small agency",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased custom-padding-top`}
      >
        <Header />
        <MainMenu />
        <PageAnimatePresence>{children}</PageAnimatePresence>
      </body>
    </html>
  );
}
